import 'dart:async';

void main() async {
  /* 

stream is a type of data - it's kind of collection can be generated by *async
generator function and yields result just like a javascript generator fn


 */

  Future<int> sumNums(Stream<int> nums) async {
    var count = 0;
    await for (var n in nums) {
      count += n;
    }
    return count;
  }

  Stream<int> someRandomNumbers(int max) async* {
    for (var i = 0; i <= max; i++) yield i;
  }

  Stream<int> someNumbers = someRandomNumbers(10);

  var result = await sumNums(someNumbers);
  print("sum from stream => $result");
}
